# Generated by Django 4.2.3 on 2025-01-03 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_gamehistory"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gameconfig",
            unique_together={("number_of_words_lvl1", "number_of_words_lvl2")},
        ),
    ]
