# Generated by Django 4.2.3 on 2025-01-03 09:26

from django.db import migrations

from app.game.consts import NUMBER_OF_OPTIONS
from app.game.models import GameConfig


def generate_game_config_data(apps, schema_editor):
    model = apps.get_model("game", "GameConfig")
    objects = []
    for i in range(NUMBER_OF_OPTIONS+1):
        objects.append(GameConfig(number_of_words_lvl1=i, number_of_words_lvl2=NUMBER_OF_OPTIONS-i))
    model.objects.bulk_create(objects)

def reverse_generate_game_config_data(apps, schema_editor):
    model = apps.get_model("game", "GameConfig")
    model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_gameconfig_unique_together"),
    ]

    operations = [
        migrations.RunPython(generate_game_config_data, reverse_code=reverse_generate_game_config_data),
    ]