# Generated by Django 4.2.3 on 2025-01-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_game_config_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameconfig",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
