# Generated by Django 4.2.3 on 2025-01-03 13:14

from django.db import migrations


def make_first_config_active(apps, schema_editor):
    model = apps.get_model("game", "GameConfig")
    first_game = model.objects.first()
    if first_game:
        first_game.is_active = True
        first_game.save()

def reverse_make_first_config_active(apps, schema_editor):
    model = apps.get_model("game", "GameConfig")
    model.objects.filter(is_active=True).update(is_active=False)

class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_gameconfig_is_active"),
    ]

    operations = [
        migrations.RunPython(make_first_config_active, reverse_code=reverse_make_first_config_active),
    ]
