# Generated by Django 4.2.3 on 2025-01-08 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_gameconfig_is_active_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="date",
            field=models.DateField(default=datetime.date(2025, 1, 8), unique=True),
            preserve_default=False,
        ),
    ]
