# Generated by Django 4.2.3 on 2025-01-13 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_game_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameconfig",
            name="number_of_words_lvl1",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="No. of complexity 1 names",
            ),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="number_of_words_lvl2",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="No. of complexity 2 names",
            ),
        ),
    ]
