# Generated by Django 4.2.3 on 2025-01-13 10:47

import app.game.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_alter_gameconfig_number_of_words_lvl1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="options_id_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                size=6,
                validators=[app.game.validators.validate_options_id_list],
            ),
        ),
    ]
