# Generated by Django 4.2.18 on 2025-10-01 14:04
import django.contrib.postgres.fields
from django.db import migrations, models
import app.game.validators


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_alter_game_options_id_list"),
    ]

    operations = [
        migrations.RunSQL(
        """
            CREATE OR REPLACE FUNCTION array_sort (ANYARRAY)
            RETURNS ANYARRAY LANGUAGE SQL
            AS $$
            SELECT ARRAY(SELECT unnest($1) ORDER BY 1)
            $$;
            
            UPDATE game_game SET options_id_list = array_sort(options_id_list) where options_id_list <> '{}';
        """,
            reverse_sql=""
        ),
        migrations.AlterField(
            model_name="game",
            name="options_id_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                size=6,
                unique=True,
                validators=[app.game.validators.validate_options_id_list],
            ),
        ),
    ]
