# Generated by Django 4.2.3 on 2023-11-06 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("algorithm", "0029_expert_review_required_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertBatchReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_completed", models.BooleanField(default=False)),
                ("bought_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "expert",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithm.resultbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.TextField()),
                ("expert_like", models.BooleanField(default=False)),
                (
                    "expert_batch_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="expert.expertbatchreview",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_review",
                        to="algorithm.result",
                    ),
                ),
            ],
        ),
    ]
