# Generated by Django 4.2.3 on 2023-11-07 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertbatchreview",
            name="expert",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Expert"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
