# Generated by Django 4.2.3 on 2023-11-13 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0002_foreign_key_expert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertbatchreview",
            name="bought_timestamp",
        ),
        migrations.AddField(
            model_name="expertbatchreview",
            name="date_started",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
