# Generated by Django 4.2.3 on 2023-11-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0003_add_date_started_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultreview",
            name="feedback",
            field=models.TextField(blank=True),
        ),
    ]
