# Generated by Django 4.2.3 on 2023-11-28 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0004_alter_resultreview_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultreview",
            old_name="feedback",
            new_name="expert_feedback",
        ),
    ]
