# Generated by Django 4.2.3 on 2024-02-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0006_alter_expertbatchreview_result_batch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertPlusReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggested_name", models.CharField(blank=True, max_length=50)),
                ("name_rationale", models.TextField(blank=True)),
                ("expert_feedback", models.TextField(blank=True)),
                (
                    "expert_batch_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_plus_reviews",
                        to="expert.expertbatchreview",
                    ),
                ),
            ],
        ),
    ]
