# Generated by Django 3.2.16 on 2023-02-13 07:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def migrate_datasets(apps, schema_editor):
    PreviousDataset = apps.get_model('core', 'Dataset')
    NewDataset = apps.get_model('algorithm', 'Dataset')
    for dataset in PreviousDataset.objects.all():
        NewDataset.objects.create(
            code=dataset.code,
            auto_generated=dataset.auto_generated,
            max_tags=dataset.auto_generated
        )


def migrate_queries(apps, schema_editor):
    PreviousQuery = apps.get_model('core', 'Query')
    NewQuery = apps.get_model('algorithm', 'Query')
    for old_query in PreviousQuery.objects.all():
        NewQuery.objects.create(
            code=old_query.code,
            temperature=old_query.temperature,
            top_p=old_query.top_p,
            max_token=old_query.max_token,
            query=old_query.query,
        )


def migrate_contents(apps, schema_editor):
    PreviousContent = apps.get_model('core', 'DatasetContent')
    NewContent = apps.get_model('algorithm', 'DatasetContent')
    NewDataset = apps.get_model('algorithm', 'Dataset')
    for content in PreviousContent.objects.all():
        new_dataset = NewDataset.objects.get(code=content.dataset.code)
        NewContent.objects.create(
            dataset=new_dataset,
            word=content.word,
            tags=content.tags
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_draftquestionnaire_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('auto_generated', models.BooleanField(default=True)),
                ('max_tags', models.IntegerField(default=20)),
                ('import_sheet', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RunPython(migrate_datasets),
        migrations.CreateModel(
            name='LMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('applied_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.75, max_digits=3)),
                ('top_p', models.DecimalField(decimal_places=2, default=0.9, max_digits=3)),
                ('max_token', models.IntegerField(default=200)),
                ('query', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'queries',
            },
        ),
        migrations.RunPython(migrate_queries),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('datasets', models.ManyToManyField(related_name='pathways', to='algorithm.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='LMMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None)),
                ('lmm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='algorithm.lmm')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='lmm',
            name='queries',
            field=models.ManyToManyField(to='algorithm.Query'),
        ),
        migrations.CreateModel(
            name='DatasetQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='algorithm.dataset')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_datasets', to='algorithm.query')),
            ],
            options={
                'verbose_name_plural': 'DatasetQueries',
                'unique_together': {('dataset', 'query')},
            },
        ),
        migrations.CreateModel(
            name='DatasetContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='algorithm.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'word')},
            },
        ),
        migrations.RunPython(migrate_contents),
    ]
