# Generated by Django 3.2.16 on 2023-02-13 08:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('first_part', models.CharField(max_length=50)),
                ('second_part', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('order', models.IntegerField()),
                ('applied_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pathway',
            name='basket_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=['RA'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathway',
            name='global_rationale',
            field=models.TextField(default='Change me'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathway',
            name='group',
            field=models.CharField(default='Change', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathway',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathway',
            name='query',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='algorithm.query'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PathwayLMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('order', models.IntegerField()),
                ('lmm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.lmm')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.pathway')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('query_mode', models.CharField(choices=[('single', 'Single Query'), ('multi', 'Multi Query'), ('custom', 'Custom Query')], max_length=10)),
                ('queries', models.ManyToManyField(to='algorithm.Query')),
            ],
        ),
    ]
