# Generated by Django 4.1.7 on 2023-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0005_query_expected_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functionresult",
            name="answers",
        ),
        migrations.AddField(
            model_name="functionresult",
            name="queries_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="functionresult",
            name="queries_started",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="functionresult",
            name="answers",
            field=models.JSONField(default=dict),
        ),
    ]
