# Generated by Django 4.1.7 on 2023-02-24 08:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0006_remove_functionresult_answers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetcontent",
            name="adjectives",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="datasetcontent",
            name="nouns",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
