# Generated by Django 4.1.7 on 2023-05-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0018_namecandidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathway",
            name="candidates_per_batch",
            field=models.IntegerField(default=0),
        ),
    ]
