# Generated by Django 4.2.1 on 2023-05-31 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0024_lmmcache"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pathway",
            name="basket_words",
        ),
    ]
