# Generated by Django 4.2.2 on 2023-06-20 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0025_remove_pathway_basket_words"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="datasetcontent",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="datasetcontent",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="pathway",
            name="datasets",
        ),
        migrations.RemoveField(
            model_name="pathway",
            name="group",
        ),
        migrations.RemoveField(
            model_name="pathway",
            name="priority",
        ),
        migrations.DeleteModel(
            name="Dataset",
        ),
        migrations.DeleteModel(
            name="DatasetContent",
        ),
    ]
