# Generated by Django 4.2.2 on 2023-06-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0026_alter_datasetcontent_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultbatch",
            name="bought_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
