# Generated by Django 4.2.3 on 2023-10-11 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_pricingplan_not_null"),
        ("algorithm", "0027_resultbatch_bought_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultbatch",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_batches",
                to="core.questionnaire",
            ),
        ),
    ]
