# Generated by Django 4.2.3 on 2023-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0028_alter_resultbatch_questionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultbatch",
            name="expert_review_reqired",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("required", "Required"),
                    ("pending", "Pending"),
                    ("done", "Done"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
