# Generated by Django 4.2.3 on 2023-11-20 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0029_expert_review_required_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultbatch",
            old_name="expert_review_reqired",
            new_name="expert_review_required",
        ),
    ]
