# Generated by Django 4.2.3 on 2024-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "algorithm",
            "0030_rename_expert_review_reqired_resultbatch_expert_review_required",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pathway",
            name="cascade_level",
            field=models.IntegerField(default=0),
        ),
    ]
