# Generated by Django 4.2.3 on 2024-01-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0031_namecandidate_rationale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namecandidate",
            name="rationale",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
