# Generated by Django 4.2.3 on 2024-02-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0031_pathway_cascade_level'),
        ('algorithm', '0032_alter_namecandidate_rationale'),
    ]

    operations = [
    ]
