# Generated by Django 3.2.16 on 2023-02-09 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_draftquestionnaire'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireevent',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.draftquestionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaireevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
