# Generated by Django 4.2.1 on 2023-06-01 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_querylog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QueryLog",
        ),
    ]
