# Generated by Django 3.2.16 on 2023-01-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataset_import_sheet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasetcontent',
            unique_together={('dataset', 'word')},
        ),
    ]
