# Generated by Django 3.2.16 on 2023-01-13 02:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_datasetcontent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=None)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.dataset')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_datasets', to='core.query')),
            ],
            options={
                'verbose_name_plural': 'DatasetQueries',
                'unique_together': {('dataset', 'query')},
            },
        ),
        migrations.DeleteModel(
            name='Lemmas',
        ),
    ]
