# Generated by Django 3.2.16 on 2023-01-13 03:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230113_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetquery',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
