# Generated by Django 3.2.16 on 2023-01-26 06:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None)),
                ('lmm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.lmm')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.questionnaire')),
            ],
        ),
    ]
