# Generated by Django 3.2.16 on 2023-02-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_draftquestionnaire_user'),
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasetcontent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='datasetcontent',
            name='dataset',
        ),
        migrations.AlterUniqueTogether(
            name='datasetquery',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='datasetquery',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='datasetquery',
            name='query',
        ),
        migrations.RemoveField(
            model_name='lmm',
            name='queries',
        ),
        migrations.RemoveField(
            model_name='lmmresult',
            name='lmm',
        ),
        migrations.RemoveField(
            model_name='lmmresult',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='datasets',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='DatasetContent',
        ),
        migrations.DeleteModel(
            name='DatasetQuery',
        ),
        migrations.DeleteModel(
            name='LMM',
        ),
        migrations.DeleteModel(
            name='LMMResult',
        ),
        migrations.DeleteModel(
            name='Pathway',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
