# Generated by Django 3.2.16 on 2023-02-15 09:27

import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230213_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftquestionnaire',
            name='name',
            field=models.CharField(default=app.core.models.default_questionnaire_name, max_length=50),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(default=app.core.models.default_questionnaire_name, max_length=50),
        ),
    ]
