# Generated by Django 4.1.7 on 2023-03-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.questionnaire",
            ),
        ),
    ]
