# Generated by Django 4.1.7 on 2023-04-07 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_questionnaire_created_questionnaire_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
