# Generated by Django 4.2.1 on 2023-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_questionnaire_failed"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_price_id", models.CharField(max_length=50)),
                ("batch_number", models.IntegerField()),
            ],
        ),
    ]
