# Generated by Django 4.2.3 on 2023-09-11 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.core.pydantic_serialization
from app.core.models.feature_config import Config, ConfigDecoder


def create_pricing_plan_a(apps, schema_editor):
    if settings.TEST:
        return
    PricingPlan = apps.get_model("core", "PricingPlan")
    db_alias = schema_editor.connection.alias
    pricing_plan = PricingPlan.objects.using(db_alias).create(name="A")

    BatchPrice = apps.get_model("core", "BatchPrice")
    BatchPrice.objects.using(db_alias).update(pricing_plan=pricing_plan)


def create_configs(apps, schema_editor):
    if settings.TEST:
        return
    FeatureConfig = apps.get_model("core", "FeatureConfig")
    db_alias = schema_editor.connection.alias
    FeatureConfig.objects.using(db_alias).bulk_create(
        [
            FeatureConfig(
                version="1.0.0",
                active=True,
                values=Config(pricing_plan="A", batch_size=24),
            ),
            FeatureConfig(
                version="1.0.1",
                active=False,
                values=Config(pricing_plan="B", batch_size=12),
            ),
        ]
    )


def reverse(apps, schema_editor):
    """
    Nothing special has to be done:

    - since BatchPrice.pricing_plan column will be deleted upon reversal
    then no need to undo the changes done to it's values;
    - since PricingPlan table will be dropped upon reversal then no need
    to delete the added record for pricing plan A from it.
    - since FeatureConfig table will be dropped upon reversal then no
    need to delete the added configs.
    """


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_batchprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
                ("version", models.CharField(max_length=15, unique=True)),
                (
                    "values",
                    models.JSONField(
                        decoder=ConfigDecoder,
                        encoder=app.core.pydantic_serialization.PydanticEncoder,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("A", "Pricing plan A (140, 110, 85, 55)"),
                            ("B", "Pricing plan B (75, 65, 55, 45)"),
                        ],
                        default="A",
                        max_length=5,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batchprice",
            name="pricing_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_prices",
                to="core.pricingplan",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(code=create_pricing_plan_a, reverse_code=reverse),
        migrations.RunPython(code=create_configs, reverse_code=reverse),
    ]
