# Generated by Django 4.2.3 on 2023-09-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_featureconfig_pricingplan_batchprice_pricing_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchprice",
            name="pricing_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_prices",
                to="core.pricingplan",
            ),
            preserve_default=False,
        ),
    ]
