# Generated by Django 4.2.3 on 2023-10-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_pricingplan_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchprice",
            name="stripe_coupon_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
