# Generated by Django 4.2.3 on 2023-11-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_batchprice_stripe_coupon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="expert_review_payed",
            field=models.BooleanField(default=False),
        ),
    ]
