# Generated by Django 4.2.3 on 2023-11-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_expert_review_payed_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("buy_more", "Buy more"),
                    ("expert_in_the_loop", "Expert in the loop"),
                ],
                max_length=25,
            ),
        ),
    ]
