# Generated by Django 4.2.3 on 2023-11-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_expert_in_the_loop_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("stripe_price_id", models.CharField(max_length=50)),
            ],
        ),
    ]
