# Generated by Django 4.2.3 on 2024-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithm", "0031_pathway_cascade_level"),
        ("core", "0030_product_price_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="pathways_run",
            field=models.ManyToManyField(blank=True, to="algorithm.pathway"),
        ),
    ]
