# Generated by Django 4.2.3 on 2024-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_product_price_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="expert_plus_payed",
            field=models.BooleanField(default=False),
        ),
    ]
