# Generated by Django 4.2.3 on 2024-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_questionnaire_expert_plus_payed"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="picks_shown",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("buy_more", "Buy more"),
                    ("expert_in_the_loop", "Expert in the loop"),
                    ("expert_plus", "Expert plus"),
                    ("experts", "Experts"),
                ],
                max_length=25,
            ),
        ),
    ]
