# Generated by Django 4.2.3 on 2024-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_questionnaire_pathways_run"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="pathways_run",
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="cascade_level_run",
            field=models.IntegerField(default=0),
        ),
    ]
