# Generated by Django 4.2.3 on 2024-02-05 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_questionnaire_picks_shown_alter_payment_payment_type"),
        ("core", "0032_remove_questionnaire_pathways_run_and_more"),
    ]

    operations = []
