# Generated by Django 4.2.3 on 2024-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reminder_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
