# Generated by Django 4.2.3 on 2024-02-23 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_user_reminder_email_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftquestionnaire",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
