# Generated by Django 4.2.3 on 2024-12-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_draftquestionnaire_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
