# Generated by Django 4.2.3 on 2025-01-06 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_questionnaire_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnaire",
            old_name="description",
            new_name="offering_description",
        ),
    ]
