# Generated by Django 4.2.17 on 2025-03-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_rename_description_questionnaire_offering_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("A", "Pricing plan A (140, 110, 85, 55)"),
                    ("B", "Pricing plan B (75, 65, 55, 45)"),
                    ("FREE", "Pricing plan FREE"),
                ],
                default="A",
                max_length=5,
                unique=True,
            ),
        ),
    ]
