# Generated by Django 4.2.17 on 2025-03-04 11:32

from django.conf import settings
from django.db import migrations

from app.core.models import PricingPlanName
from app.core.models.feature_config import Config


def create_pricing_plan_free(apps, schema_editor):
    if settings.TEST:
        return
    PricingPlan = apps.get_model("core", "PricingPlan")
    db_alias = schema_editor.connection.alias
    PricingPlan.objects.using(db_alias).create(name="FREE")


def create_configs(apps, schema_editor):
    if settings.TEST:
        return
    FeatureConfig = apps.get_model("core", "FeatureConfig")
    db_alias = schema_editor.connection.alias
    FeatureConfig.objects.using(db_alias).filter(active=True).update(active=False)
    feature_config =  FeatureConfig(
        version="1.0.2",
        active=True,
        values=Config(pricing_plan=PricingPlanName.FREE, batch_size=24),
    )
    feature_config.save()


def reverse(apps, schema_editor):
    """
    Nothing special has to be done:

    - since PricingPlan table will be dropped upon reversal then no need
    to delete the added record for pricing plan A from it.
    - since FeatureConfig table will be dropped upon reversal then no
    need to delete the added configs.
    """


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_pricingplan_name"),
    ]

    operations = [
        migrations.RunPython(code=create_pricing_plan_free, reverse_code=reverse),
        migrations.RunPython(code=create_configs, reverse_code=reverse),
    ]
